// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLImml2_O_jD2nxnXrm7dAHls3bCeTXaw',
    appId: '1:1035124228985:web:1206a704d703a037dc65a8',
    messagingSenderId: '1035124228985',
    projectId: 'flower-app-674ae',
    authDomain: 'flower-app-674ae.firebaseapp.com',
    storageBucket: 'flower-app-674ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PxkcPBQ8Krczoyn7389PnAXviN-efTw',
    appId: '1:1035124228985:android:c3c1b9f86d6c6649dc65a8',
    messagingSenderId: '1035124228985',
    projectId: 'flower-app-674ae',
    storageBucket: 'flower-app-674ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkCbRk8CVTivZayGNQ6SHAVDRVaJTrig',
    appId: '1:1035124228985:ios:15872c9b986029a1dc65a8',
    messagingSenderId: '1035124228985',
    projectId: 'flower-app-674ae',
    storageBucket: 'flower-app-674ae.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOkCbRk8CVTivZayGNQ6SHAVDRVaJTrig',
    appId: '1:1035124228985:ios:d53e378102086b0fdc65a8',
    messagingSenderId: '1035124228985',
    projectId: 'flower-app-674ae',
    storageBucket: 'flower-app-674ae.appspot.com',
    iosBundleId: 'com.example.flowerApp.RunnerTests',
  );
}
